#!/bin/bash

# bash <(curl -sSL https://bit.ly/beekeeper-ensure-latest)

dry_run() {
  echo "$@"
}

run() {
  "$@"
}

double_check() {
  local good_to_go=''
  read -s -p "press 'y' to run this command"$'\n' -n 1 good_to_go
  if [[ "$good_to_go" == 'y' ]]; then
    return 0
  fi
  return 1
}

safe_run() {
  dry_run "$@"
  double_check || return 0
  run "$@"
  echo ''
}

main() {
  safe_run brew update
  safe_run brew install gump
  safe_run brew upgrade gump
  safe_run brew install ensure-project
  safe_run brew upgrade ensure-project
  safe_run ensure-project dotfiles
  safe_run ensure-project octoswarm
  safe_run ensure-project swarm-prod
  safe_run npm uninstall --global deploy-state-util
  safe_run npm install --global beekeeper-util
  echo ''
  echo '!! IMPORTANT'
  echo 'If you have not yet installed dotfiles, follow the instructions in the dotfiles README'
  echo ''
  echo "Make sure you have the latest docker for mac beta installed"
  echo ''
}

main "$@"
